apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: notifications
data:
  REDIS_ADDR: redis:6379
  JWT_JWKS_URL: http://your-idp/.well-known/jwks.json
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
